### ISSUE TITLE
Unable to connect to the address ?

### ISSUE THREAD

**Issue by anweshknayak** [Cloud-CV/cvfy-frontend#27] opened 2016-12-22 09:47 UTC
Node version: 6.9.0

npm version: 4.0.3

Operating system: 14.04

Command line used:

Steps to reproduce:

I have tried both the installation procedures. But I cannot simply open the link ? Can you help a bit here

**Comment by anweshknayak** [comment] 2016-12-22 09:54
I even tried using the alternate version without docker. It simpy doesn't connect to the address in the outCalls/config.js file

**Comment by tocttou** [comment] 2016-12-22 09:58
Be more specific.
1. Where do you see this error, add some screenshot if necessary?
2. What command caused this error?
3. Did you setup the database before trying?

**Comment by anweshknayak** [comment] 2016-12-22 10:12
![screenshot from 2016-12-22 15 31 07](https://cloud.githubusercontent.com/assets/8139783/21422159/753ae206-c85c-11e6-8e76-ebe4f13fd8be.png)

2. docker run -d -p 5005:5001 --restart=always cvfy

3. Yes.

**Comment by tocttou** [comment] 2016-12-22 10:15
Do you want to work on fixing this? :smile: 

You'll need to build the app outside of docker to see the issue.

**Comment by tocttou** [comment] 2016-12-22 10:20
I tried a new build, the issue is a breaking change introduced in React 15.4.1 last month.

https://github.com/zilverline/react-tap-event-plugin/issues/85

@anweshknayak you may want to look into this.

**Comment by anweshknayak** [comment] 2016-12-22 10:23
@tocttou sure I would like to work on this. :)

**Comment by tocttou** [comment] 2016-12-22 10:36
Issue is fixed now. Bundle is produced without errors and I am able to use the app. I have included a lock file with exact dependency versions. You may want to use https://yarnpkg.com/ instead of `npm` in the "without docker" method. Please confirm that it works.

**Comment by anweshknayak** [comment] 2016-12-22 20:10
@tocttou yarn install says unable to connect to the server ? 
I am not under any proxy server as of now.

**Comment by anweshknayak** [comment] 2016-12-23 04:02
seems like this https://github.com/yarnpkg/yarn/issues/668

**Comment by tocttou** [comment] 2016-12-23 08:48
That is an issue on your end.

**Comment by anweshknayak** [comment] 2016-12-23 17:19
fixed. closing this.

**Comment by anweshknayak** [comment] 2016-12-23 23:31
yarn issue persists. could you fix the npm dependencies? or tell me If I can do anything to fix it.

**Comment by tocttou** [comment] 2016-12-24 08:59
I told you its an issue with your installation of yarn. You can always use `npm` as usual instead.

**Comment by tocttou** [comment] 2016-12-24 09:06
Delete the `node_modules` folder and the `yarn.lock` file and try again.

**Comment by tocttou** [comment] 2016-12-24 09:21
@anweshknayak I tried a new build from scratch and it works fine. Lock file is correct. Dependencies are correct. Fix your installation of yarn or just use npm otherwise like mentioned in the steps. The exact steps are:
-x-x-x-
1. start a mongodb instance at port 27017 (default)
2. git clone <this-repo>
3. yarn (better) or npm install
4. yarn/npm run build -s
5. yarn/npm start -s
6. visit localhost:5001

I am closing this.

**Closed by tocttou** 2016-12-24 09:21 UTC
